###########
# GENERAL #
###########

# Import additional configuration files
import = ["~/.config/alacritty/themes/themes/hyper.toml"]
# Shell program and its arguments
# Default for Linux/BSD/macOS is $SHELL or user's login shell
# Default for Windows is "powershell"
#[shell]
#program = "/bin/zsh"  # Example for Linux/BSD/macOS
#args = ["-l"]
working_directory = "None"  # Default: "None"
live_config_reload = true  # Default: true
ipc_socket = true  # Default: true

#######
# ENV #
#######

[env]
# Environment variables
TERM = "xterm-256color"

##########
# WINDOW #
##########

[window]
dimensions = { columns = 0, lines = 0 }  # Default: columns = 0, lines = 0
position = "None"  # Default: "None"
padding = { x = 0, y = 0 }  # Default: x = 0, y = 0
dynamic_padding = false  # Default: false
decorations = "Buttonless"  # Default: "Full"
opacity = 0.85  # Default: 1.0
blur = false  # Default: false
startup_mode = "Windowed"  # Default: "Windowed"
title = "Alacritty"  # Default: "Alacritty"
dynamic_title = true  # Default: true
class = { instance = "Alacritty", general = "Alacritty" }  # Default: instance = "Alacritty", general = "Alacritty"
decorations_theme_variant = "None"  # Default: "None"
resize_increments = false  # Default: false
option_as_alt = "None"  # Default: "None"

#############
# SCROLLING #
#############

[scrolling]
history = 10000  # Default: 10000
multiplier = 1  # Default: 3

########
# FONT #
########

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic
size = 14  # Default: 11.25
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
builtin_box_drawing = true  # Default: true

##########
# COLORS #
##########

[colors]
transparent_background_colors = true # Default
draw_bold_text_with_bright_colors = false  # Default
[colors.primary]
#foreground = "#d8d8d8"  # Default
#background = "#181818"  # Default
#dim_foreground = "#828482"  # Default
#bright_foreground = "None"  # Default
[colors.cursor]
#text = "CellBackground"  # Default
#cursor = "CellForeground"  # Default
[colors.vi_mode_cursor]
#text = "CellBackground"  # Default
#cursor = "CellForeground"  # Default
[colors.search.matches]
#foreground = "#181818"  # Default
#background = "#ac4242"  # Default
#foreground = "#181818"  # Default
#background = "#f4bf75"  # Default
[colors.hints.start]
#foreground = "#181818"  # Default
#background = "#f4bf75"  # Default
#foreground = "#181818"  # Default
#background = "#ac4242"  # Default
[colors.line_indicator]
#foreground = "None"  # Default
#background = "None"  # Default
[colors.footer_bar]
#foreground = "#181818"  # Default
#background = "#d8d8d8"  # Default

# Selection colors
[colors.selection]
#text = "CellBackground"  # Default
#background = "CellForeground"  # Default

# Normal colors
[colors.normal]
#black = "#181818"  # Default
#red = "#ac4242"  # Default
#green = "#90a959"  # Default
#yellow = "#f4bf75"  # Default
#blue = "#6a9fb5"  # Default
#magenta = "#aa759f"  # Default
#cyan = "#75b5aa"  # Default
#white = "#d8d8d8"  # Default

# Bright colors
[colors.bright]
#black = "#6b6b6b"  # Default
#red = "#c55555"  # Default
#green = "#aac474"  # Default
#yellow = "#feca88"  # Default
#blue = "#82b8c8"  # Default
#magenta = "#c28cb8"  # Default
#cyan = "#93d3c3"  # Default
#white = "#f8f8f8"  # Default

# Dim colors
[colors.dim]
#black = "#0f0f0f"  # Default
#red = "#712b2b"  # Default
#green = "#5f6f3a"  # Default
#yellow = "#a17e4d"  # Default
#blue = "#456877"  # Default
#magenta = "#704d68"  # Default
#cyan = "#4d7770"  # Default
#white = "#8e8e8e"  # Default

########
# BELL #
########

[bell]
animation = "Linear"  # Default: "Linear"
duration = 0  # Default: 0
color = "#ffffff"  # Default: "#ffffff"
command = "None"  # Default: "None"

#############
# SELECTION #
#############

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = false  # Default: false

##########
# CURSOR #
##########

[cursor]
style = { shape = "Beam", blinking = "On" }  # Default: shape = "Block", blinking = "Off"
vi_mode_style = "None"  # Default: "None"
blink_interval = 750  # Default: 750
blink_timeout = 0  # Default: 5
unfocused_hollow = true  # Default: true
thickness = 0.15  # Default: 0.15

############
# TERMINAL #
############

[terminal]

# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste"  # Default: "OnlyCopy"

#########
# MOUSE #
#########

[mouse]

# When true, the cursor is temporarily hidden when typing
hide_when_typing = true  # Default: false

# Mouse bindings (actual bindings need to be defined as per user preference)
# Example: bindings = [{ mouse = "Left", action = "Paste" }]
bindings = []

#########
# HINTS #
#########

[hints]

# Define the keys used for hint labels
alphabet = "jfkdls;ahgurieowpq"  # Default: "jfkdls;ahgurieowpq"

# Enable specific hints
#[[hints.enabled]]
# Example configuration (actual settings to be defined based on user preference)
# regex = "..."
# hyperlinks = true
# post_processing = true
# persist = false
# action = "..."
# command = "..."
# binding = { key = "...", mods = "...", mode = "..." }
# mouse = { mods = "...", enabled = true }

# KEYBOARD section of Alacritty configuration

[keyboard]

# Define keyboard bindings here
# Example placeholder (actual bindings need to be defined based on user preference)
bindings = [
    # { key = "Key", mods = "Modifiers", action = "Action" },
    # { key = "Key", mods = "Modifiers", chars = "Characters to send" },
    # ...
]
